### ISSUE TITLE
Slow rendering. 

### ISSUE THREAD

**Issue by thomasdavis** [mudassir0909/jsonresume-theme-elegant#105]
Hey man, hope everything is well with you. 

I'm still using Elegant as my default theme but noticed on the new serverless infrastructure it is kind of relatively slow to render -> https://registry.jsonresume.org/thomasdavis

Compared to
https://registry.jsonresume.org/thomasdavis?theme=pumpkin
https://registry.jsonresume.org/thomasdavis?theme=paper

Seems like there isn't really a reason why it shouldn't be instant-ish

(There is a delay for all themes when fetching the resume on serverless stack)

**Comment by mudassir0909** [comment]
Shall take a look this weekend

It's been a while since I worked on this :D

**Comment by mudassir0909** [comment]
Can you confirm if #106 fixed it? I couldn't see any noticeable change on https://registry.jsonresume.org/thomasdavis, where can I look into the server side logic to get a few extra pointers?

**Comment by thomasdavis** [comment]
I suck, sorry for the lateness. 

Just deployed the new version but getting errors now 

```

TypeError: Cannot read property 'forEach' of undefined     at Object.render (/srv/node_modules/jsonresume-theme-elegant/index.js:82:19)     at resumeSchema.validate (/srv/index.js:187:40)     at callbackWrapper (/srv/node_modules/resume-schema/validator.js:17:7)     at /srv/node_modules/z-schema/src/Report.js:46:13     at _combinedTickCallback (internal/process/next_tick.js:132:7)     at process._tickDomainCallback (internal/process/next_tick.js:219:9) | more_vert
-- | --
```

**Comment by thomasdavis** [comment]
Ah just looks like my resume was missing `awards`. 

I imagine the theme breaks on anything where a field is missing 

`resume.education.forEach`

**Comment by thomasdavis** [comment]
Looks like lodash use to handle it gracefully.

**Comment by mudassir0909** [comment]
> Ah just looks like my resume was missing awards.

Ah, thanks for the catch. I imagined to be empty array, didn't expect the following to be nullable 

https://github.com/jsonresume/resume-schema/blob/6008d314247dee62d22875e1f7425ed17db3750d/schema.json#L234-L236

Either way, updated to use `_(...).forEach`
