### ISSUE TITLE
Implement "certificates" section

### ISSUE THREAD

**Issue by maksymgendin** [mudassir0909/jsonresume-theme-elegant#132]
The [official schema](https://github.com/jsonresume/resume-schema/blob/master/schema.json) supports a `certificates` block, it would be great to have support for that ❤️

**Comment by maksymgendin** [comment]
@mudassir0909 I've created a [pull request](https://github.com/mudassir0909/jsonresume-theme-elegant/pull/133) for this 😊

**Comment by mudassir0909** [comment]
Thank you! merged  🎉

**Comment by maksymgendin** [comment]
@mudassir0909 Nothing to thank for 😊 Is there a chance to get this published to NPM so that https://github.com/jsonresume/theme-manager will start using the new version with the certificates?

**Comment by maksymgendin** [comment]
I made a pull request here: https://github.com/jsonresume/registry-functions/pull/39
Not sure what the correct process is, hope this is ok :smile:

**Comment by mudassir0909** [comment]
Hey it’s already published to npm, can you check if it’s working for you? Let me know if it isn’t
On 3 Apr 2021, 9:58 PM +1100, Maksym Gendin ***@***.***>, wrote:
> @mudassir0909 Nothing to thank for 😊 Is there a chance to get this published to NPM so that https://github.com/jsonresume/theme-manager will start using the new version with the certificates?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
**
** <https://www.canva.com/>Empowering the world to design
Share accurate 
information on COVID-19 and spread messages of support to your community.
Here are some resources 
<https://about.canva.com/coronavirus-awareness-collection/?utm_medium=pr&utm_source=news&utm_campaign=covid19_templates> 
that can help.
 <https://twitter.com/canva> <https://facebook.com/canva> 
<https://au.linkedin.com/company/canva> <https://twitter.com/canva>  
<https://facebook.com/canva>  <https://au.linkedin.com/company/canva>  
<https://instagram.com/canva>

**Comment by maksymgendin** [comment]
@mudassir0909 Yes, it works when fetched from NPM, thanks!
However seems like it will take some time till it will be used on https://jsonresume.org 😄
In the end I switched to a self-hosted version and there it works like a charme: https://gendin.info/resume.html

**Comment by mudassir0909** [comment]
Yeah, it would work if and when certificates get accepted as part of the resume schema

**Comment by mudassir0909** [comment]
May I know what's your jsonresume URL? It seems to be part of the schema [here](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json)

**Comment by maksymgendin** [comment]
@mudassir0909 https://registry.jsonresume.org/maksymgendin

Yes, it's part of the schema, see my first comment.

Bit I think [my merge request](https://github.com/jsonresume/registry-functions/pull/39) has to be merged first for a version upgrade and redeploy to Firebase Functions.

**Comment by mudassir0909** [comment]
> But I think my merge request has to be merged first for a version upgrade and redeploy to Firebase Functions.

Oh I see. I thought it always picked up the latest by default ? This behavior might have been changed recently
