### ISSUE TITLE
Custom avatar is not loaded into the JSON resume

### ISSUE THREAD

**Issue by lananolana** [mudassir0909/jsonresume-theme-elegant#158]
## Description
The default image is displayed in place of the avatar instead of the actual image that is added into the resume.json file. The problem is only in the Elegant theme. At first the issue was opened [here](https://github.com/jsonresume/resume-schema/issues/469).

## Steps
**Preconditions**: JSON resume with Elegant theme is uploaded as a gist without an image link.

1. Copy the avatar URL, for example [my GitHub avatar](https://avatars.githubusercontent.com/u/107322490?v=4)
2. Paste the URL into `resume.json` file and update the public gist.
4. Refresh the resume page ([https://registry.jsonresume.org/](https://registry.jsonresume.org/)`{your_github_username}`)

## Actual result
The default image is displayed in place of the avatar.
### Image URL in the `resume.json`: 
![Actual link](https://github.com/jsonresume/resume-schema/assets/107322490/2827221a-2c88-455a-89a2-426cbf3efb53)
### Actual image URL on the page: 
![Error link](https://github.com/jsonresume/resume-schema/assets/107322490/e901c2d6-bf34-4729-91df-58940acbb29e)

## Expected result
The picture whose link is added to the `resume.json` file is displayed in place of the avatar.

## Additional links
- Link to [my resume.json file](https://gist.github.com/lananolana/2b3f0a128cda86e99028654f029d841f)
- Refer to your `index.js` file:
https://github.com/mudassir0909/jsonresume-theme-elegant/blob/1b38dae2f9fcdf0e4a5d03d2a737b88303ff6305/index.js#L21

**Comment by SkepticMystic** [comment]
I experience the same issue. Only happens with the elegant theme

**Comment by pogmommy** [comment]
This issue is explained [here](https://github.com/mudassir0909/jsonresume-theme-elegant/issues/149#issuecomment-1159021846). The theme erroneously uses `basics.picture` instead of `basics.image`.

Changing `"image": "https://url.com/image.jpg"` to `"picture": "https://url.com/image.jpg"` (or just adding the latter) fixed the issue for me

**Comment by lananolana** [comment]
Thanks @pogmommy for the link to the issue, it surely works as you said. I'll close this one as a duplicate.
