### ISSUE TITLE
Add Markdown support

### ISSUE THREAD

**Issue by mudassir0909** [mudassir0909/jsonresume-theme-elegant#18]
Based on https://github.com/jsonresume/resume-schema/issues/47 , https://github.com/jsonresume/resume-cli/issues/61

**Comment by oupala** [comment]
I'll be happy to see this feature available as it is the last really needed feature to produce complete resumes.

**Comment by mudassir0909** [comment]
@oupala  [Markdown is now supported](https://github.com/mudassir0909/jsonresume-theme-elegant#markdown-supported)

**Comment by oupala** [comment]
Thanks @mudassir0909 for this feature. It works well.

The supported field are wider than you mention in [your documentation](https://github.com/mudassir0909/jsonresume-theme-elegant#markdown-supported). I'm also using markdown links in `work[0].highlight`, `volunteer[0].organization`, `education[0].institution`.

Unfortunately, there is some bug the markdown parser `marked`. I will some issues about that.
