### ISSUE TITLE
Spotify profile URL not working

### ISSUE THREAD

**Issue by chrisvogt** [mudassir0909/jsonresume-theme-elegant#28]
Not sure where the current Spotify profile URL came from - perhaps it was valid in the past. The correct profile URL should reference the `play` or `open` subdomain like so:

     https://open.spotify.com/user/artinreality

(_See:_ https://twitter.com/nicklas2k/status/330112083964342273)

I'm sending a pull request updating the URL in one minute.

**Comment by mudassir0909** [comment]
Thanks for the PR, Spotify is not available in my country. So, I googled for the term "spotify user" & I found one profile which had the url similar to the one I've included.

**Comment by chrisvogt** [comment]
That's sad. I see that now on [this Quora post](http://www.quora.com/Why-is-Spotify-not-available-in-India). What do you use instead of Spotify? Grooveshark is a nice alternative if it works in your country.

**Comment by mudassir0909** [comment]
I use itunes, there are free alternatives like gaana.com & saavn.com
