### ISSUE TITLE
PDF Weirdness on OSX

### ISSUE THREAD

**Issue by ilsken** [mudassir0909/jsonresume-theme-elegant#41]
I'm getting this when I export to a PDF
![image](https://cloud.githubusercontent.com/assets/554927/7307775/03c15f1a-e9dd-11e4-9f53-839a3e68a107.png)

**Comment by mudassir0909** [comment]
I know, there are issues with pdf export via command line because print.css is not being applied properly. Open the resume in chrome just do a `cmd + p` and then save as pdf for now.
