### ISSUE TITLE
Add exercism.io to Supported Social Profiles

### ISSUE THREAD

**Issue by jalyna** [mudassir0909/jsonresume-theme-elegant#46]
As [exercism.io](http://exercism.io) might contain some code snippets it would be cool to add it. An icon can be found here:

http://exercism.io/icons/logo.svg
http://exercism.io/img/e_red_small.png

Thanks for this nice resume theme :+1:

**Comment by mudassir0909** [comment]
Thanks :)

Can you give me an example of an example exercism(I tend to type exorcism :smile:) profile ? So, that I can construct the url based on the username

**Comment by jalyna** [comment]
mine would be http://exercism.io/jalyna :) thanks!

**Comment by mudassir0909** [comment]
But this doesn't look like public profile, it asks me to login or they don't have public profile et all ? I did some googling but did not find any. If there is not public profile then will proceed with this one

**Comment by mudassir0909** [comment]
@jalyna Exercism is now supported, but you can't verify it until https://github.com/jsonresume/theme-manager/issues/23 is fixed
