### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by thomasdavis** [mudassir0909/jsonresume-theme-elegant#51]
Is the latest version working? http://themes.jsonresume.org/theme/elegant

**Comment by mudassir0909** [comment]
Thanks for the pointer :+1: , it was working on local because the server & the `index.jade` were both in same directory. https://github.com/mudassir0909/jsonresume-theme-elegant/commit/180c32a1aff587c7fc13ab54efda4a9dbb69ede1 fixed the issue now :)
