### ISSUE TITLE
Wrong Month Calculation

### ISSUE THREAD

**Issue by MiteshShah** [mudassir0909/jsonresume-theme-elegant#58]
Refer: http://150.107.225.81:8888/#work-experience 
<img width="367" alt="screen shot 2015-12-28 at 5 18 32 pm" src="https://cloud.githubusercontent.com/assets/1223371/12018319/1d02ca86-ad87-11e5-979f-bd7499c05a34.png">

From 1st April to 30 Nov its 8 Months not 7 Months
```
1. April
2. May
3.June
4.July
5.Aug
6.Sep
7.Oct
8.Nov
```

**Comment by mudassir0909** [comment]
Technically `7 months 29 days`, right now I'm not displaying the days diff if year diff > 0 or month diff > 0 because the precision of the kind `1 year 10 months 12 days` is not generally needed
 
https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/moment-precise-range.js#L72

Do you have better ideas?

**Comment by MiteshShah** [comment]
@mudassir0909 

Wrong Logic: 

```
Start Date: 2014-04-01
End Date: 2014-11-30
````
https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/moment-precise-range.js#L37
```
var dDiff = m2.date() - m1.date();
dDiff = 30-01= 29
```
Instead of that we have to check m2.date is End Of Month Date the Month+1

**Comment by MiteshShah** [comment]
@mudassir0909 Refer: http://150.107.225.81:8888/#about

Its better to display 2 years instead of 1 year 11 months 30days 
<img width="391" alt="screen shot 2015-12-28 at 6 01 48 pm" src="https://cloud.githubusercontent.com/assets/1223371/12018744/19e6d44a-ad8d-11e5-99a3-ff32830f895f.png">

**Comment by mudassir0909** [comment]
Agreed with the calculation, if the `startDate` is beginning of a month & `endDate` is the end of the month, we should increment month count

**Comment by MiteshShah** [comment]
@mudassir0909 Sorry not good in js/css to submit this pull request :(

**Comment by mudassir0909** [comment]
no problem, I'll look into it when I get some free time, thanks for pointing out the issue though :)

**Comment by oupala** [comment]
I'm encountering the exact same problem. I'll be happy to see this bug fixed.

**Comment by oupala** [comment]
It works flawlessly. Thank you @mudassir0909 !

**Comment by mudassir0909** [comment]
:blush:
