### ISSUE TITLE
URL in job descriptions

### ISSUE THREAD

**Issue by alistra** [mudassir0909/jsonresume-theme-elegant#61]
Is there a way to provide links to your projects (in my case iTunes Connect links) somewhere in the job section?

Currently all the text is provided as is, so the links pasted are just there, not clickable. There's also no way to do a `<a>` tag injection.

Is this something that should be considered at the jsonresume schema or do you have any idea how to accomplish this?

**Comment by mudassir0909** [comment]
yes I do have an idea, I'll implement markdown support soon(read this weekend), then you can easily embed links using the markdown format

**Comment by mudassir0909** [comment]
[Markdown is now supported](https://github.com/mudassir0909/jsonresume-theme-elegant#markdown-supported). So you can now update your `work[0].summary` to define a link in markdown format, following is an example

<img width="709" alt="screen shot 2016-03-19 at 1 27 15 pm" src="https://cloud.githubusercontent.com/assets/1861842/13897385/16339318-edd6-11e5-8df8-16ae09f67057.png">

That code will render the following

<img width="551" alt="screen shot 2016-03-19 at 1 28 56 pm" src="https://cloud.githubusercontent.com/assets/1861842/13897392/5525f980-edd6-11e5-9f9e-575a18b02115.png">
