### ISSUE TITLE
New lines in bodies of text are ignored.

### ISSUE THREAD

**Issue by alistra** [mudassir0909/jsonresume-theme-elegant#62]
When I try to put `"\n"` in the JSON strings, it gets ignored by the template. It probably should transform newlines into `<br>` tags. As currently it probably adds new lines to the HTML, which doesn't affect line breaks.

**Comment by mudassir0909** [comment]
I've a plan to implement markdown support https://github.com/mudassir0909/jsonresume-theme-elegant/issues/18 

I'm so busy with my work these days, will be happy to see a PR

**Comment by mudassir0909** [comment]
[Markdown is now supported](https://github.com/mudassir0909/jsonresume-theme-elegant#markdown-supported)
