### ISSUE TITLE
Social icons are not displayed in Firefox

### ISSUE THREAD

**Issue by stieben** [mudassir0909/jsonresume-theme-elegant#64]
My setup:

- **Firefox** for Ubuntu, version 44.0.2
- elementary OS 0.3.2 Freya (64-bit), based on **Ubuntu** 14.04

**Comment by mudassir0909** [comment]
Can you post a screenshot?

**Comment by stieben** [comment]
Same problem with Firefox 44.0.2 on Windows 10 Pro (64-bit):

![No social icons in FF on Win 10](https://cloud.githubusercontent.com/assets/9888741/13076820/47b56a90-d4b5-11e5-8582-43f8f03e4e42.jpg)

Strangely enough, it does work in the theme editor (also FF on Win 10):

![Social icons in FF on Win 10](https://cloud.githubusercontent.com/assets/9888741/13076844/74ed1a80-d4b5-11e5-88c7-2c1199c1aa3a.jpg)

**Comment by mudassir0909** [comment]
which means media query related issues?

**Comment by mudassir0909** [comment]
Also, if you into frontend, can you just inspect element & see the css styling ? If not we can do screenshare or something & resolve this

**Comment by stieben** [comment]
The inspection reveals that [there's no `::before` element](http://themes.jsonresume.org/theme/elegant):

![No ::before element](https://cloud.githubusercontent.com/assets/9888741/13206069/3d369c24-d8f7-11e5-8794-3f11133d412c.png)

Whereas [in the theme editor there is](http://registry.jsonresume.org/#elegant):

![::before element exists](https://cloud.githubusercontent.com/assets/9888741/13206076/5a2fba68-d8f7-11e5-9e3d-20d003c0d96f.png)

So it's not a media query related issue. But there's another correlation I noticed in the theme editor (where the icons are displayed) – there's no active JavaScript:

- [email protected]
- No tooltips
- Menu not working

**Comment by mudassir0909** [comment]
thanks alot for the screnshots. Maybe pseudo selectors are not supported? but then it's firefox 44!

I just tested on [browserstack](https://www.browserstack.com), Windows 10, Firefox v44 & it doesn't seem to happen. Maybe it's the problem with your browser? did you turn on/off any flags(not sure if firefox has experimental flags similar to chrome)?

<img width="1280" alt="screen shot 2016-02-22 at 12 49 42 pm" src="https://cloud.githubusercontent.com/assets/1861842/13211915/c924aabc-d962-11e5-92d2-86a17ae2aedc.png">

**Comment by stieben** [comment]
Your browserstack screen shot ultimately confused me and I almost decided to surrender. And then your remark about flags made me think – I don't have set any but I decided to take a look at my addons. And there it was:

**[Adblock Plus](https://adblockplus.org/) caused the issue.**

![facepalm](http://i0.kym-cdn.com/entries/icons/original/000/000/554/facepalm.jpg)

Thanks for your assistance and your time!

**Comment by mudassir0909** [comment]
glad to know, it is resolved :)
