### ISSUE TITLE
Markdown in highlights

### ISSUE THREAD

**Issue by alistra** [mudassir0909/jsonresume-theme-elegant#69]
There's a highlights field under `work[0].highlights[0]` - I would like for it to support markdown, as I wanted to paste URLs to my work projects there

**Comment by alistra** [comment]
As currently it looks like this ![](http://cl.ly/2I1s0m0y0S0r/Screen%20Shot%202016-03-20%20at%2023.25.12.png)

**Comment by mudassir0909** [comment]
As mentioned I had implemented only inside the `work[0].summary` will add it to highlights as well

**Comment by mudassir0909** [comment]
Fixed in 71953a4a824c4573db131f07b556c37c2d1d0fb2
