### ISSUE TITLE
layout bug: .skill-info

### ISSUE THREAD

**Issue by aljachimiak** [mudassir0909/jsonresume-theme-elegant#70]
Looks like a [recent commit](https://github.com/mudassir0909/jsonresume-theme-elegant/commit/7841e7740287c7285c8dc3468cfce041f3119e48#diff-e3f2d991bd60c33201db79f319600a3bL821) removed a css style for `.skill-info`.

![screen shot 2016-03-26 at 8 48 48 am](https://cloud.githubusercontent.com/assets/1467678/14060119/a735920e-f32f-11e5-9b06-80e4f6aa4333.png)

After playing with it in Chrome, the removed 10px seems to be a bit too close...

````
.skill-info { margin-left: 1em; }
````
or
````
.skill-info { margin-left: 16px; }
````
seems like they would work.

**Comment by mudassir0909** [comment]
my bad! yes the `10px` is too close right now because the section used to have `5px` padding-left. So the ideal margin now would be `15px`. Thanks for pointing this out!
