### ISSUE TITLE
markdown links ending with ")" are not correctly converted

### ISSUE THREAD

**Issue by oupala** [mudassir0909/jsonresume-theme-elegant#74]
markdown links ending with ")" are not correctly converted.

Such links are often encountered in wikipedia.

The bug comes from marked (chjj/marked#619) and it appears that it won't be fixed.

It's maybe time to switch the markdown renderer... (see #73).

**Comment by mudassir0909** [comment]
can you make that change if you are free, I'll be busy for couple more weeks. It's just switching the npm library that we use & modify a single line [here](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/index.js#L31)

**Comment by oupala** [comment]
I tried to replace marked by markdown-it but generating the resume fails due to the absence of the marked library, I must have missed some build step:

```bashmodule.js:440
    throw err;
    ^

Error: Cannot find module 'marked'
```

Please help me with some more information so I can test markdown-it.

**Comment by mudassir0909** [comment]
can you commit your changes so that I can see what's going wrong?

**Comment by oupala** [comment]
Here are the changes I've done on my local install: https://github.com/oupala/jsonresume-theme-elegant/commits/oupala-patch-1

I've just edited the files on my local directory.

**Comment by mudassir0909** [comment]
Made the changes :)

**Comment by oupala** [comment]
It works perfectly!
