### ISSUE TITLE
Icon Request: icon-blogger

### ISSUE THREAD

**Issue by amowu** [mudassir0909/jsonresume-theme-elegant#76]
Hi, I like this theme and use on my [resume](http://amowu.github.io/resume/).

But when I try to add blogger icon, I can't setting **Encode & Embed Font in CSS** on IcoMoon (it's premium)

![screen shot 2016-04-30 at 3 05 59 am](https://cloud.githubusercontent.com/assets/559351/14926785/83b23c76-0e80-11e6-9770-b51fa3de1573.png)

So I open this issue, thank you!

**Comment by mudassir0909** [comment]
Can you send me the svg file or the link to svg file?

**Comment by amowu** [comment]
@mudassir0909 OK

[blogger.svg.zip](https://github.com/mudassir0909/jsonresume-theme-elegant/files/246699/blogger.svg.zip)

**Comment by mudassir0909** [comment]
thanks!

**Comment by mudassir0909** [comment]
Blogger is now supported!

If your url is `google.blogspot.com` then add username as `google` or you can just update the `url` attribute to have the url
```json
      {
        "network": "blogger",
        "username": "google",
        "url": ""
      }
```
