### ISSUE TITLE
Flickr social profile support

### ISSUE THREAD

**Issue by 47ronin** [mudassir0909/jsonresume-theme-elegant#77]
Great theme. Please consider including Flickr in the supported social profiles. I believe iconmoon has four font glyphs for Flickr. Thanks!

**Comment by mudassir0909** [comment]
Sure, will add this weekend

**Comment by mudassir0909** [comment]
Flickr is now supported please add the following in your `resume.basics.profiles`

```
      {
        "network": "flickr",
        "username": "your_flickr_username",
        "url": ""
      }
```

Do let me know if you face any issues
