### ISSUE TITLE
Support for meetup.com profiles?

### ISSUE THREAD

**Issue by deeplook** [mudassir0909/jsonresume-theme-elegant#78]
I like using this theme (big thanks!), but would much appreciate a profile for meetup.com member pages like this one as well: http://www.meetup.com/members/75934402/ I'm not sure the code is as modular that making such contributions would be an easy thing to do (or is it?).

**Comment by mudassir0909** [comment]
It indeed is easy except for integrating the icon 😊 

Create a pull request on [this repo](https://github.com/jsonresume/theme-utils), In that repo edit [this method](https://github.com/jsonresume/theme-utils/blob/master/basics.js#L50) to support meetup OR else wait until the weekend I'll add the support

**Comment by mudassir0909** [comment]
Meetup is now supported please add the following in your `resume.basics.profiles`

```
      {
        "network": "meetup",
        "username": "75934402",
        "url": ""
      },
```

**Comment by mudassir0909** [comment]
Do let me know if you face any issues

**Comment by deeplook** [comment]
Works great, thanks!
