### ISSUE TITLE
How to Configure Gravatar

### ISSUE THREAD

**Issue by jamespedwards42** [mudassir0909/jsonresume-theme-elegant#80]
I have my picture configured as:
 ```"picture": "https://www.gravatar.com/avatar/01667e959f76bdd16a1930a67f393a51",```

Everything else is generated fine, but I end up with the following displayed instead of an image:

https://www.gravatar.com/avatar/01667e959f76bdd16a1930a67f393a51?s=100&r=pg&d=mm" itemprop="image" class="media-object img-circle center-block"/>

**Comment by mudassir0909** [comment]
When it's gravatar you don't need to specify the url, the theme picks up the url from the email address, Here is an example `https://github.com/mudassir0909/resume/blob/master/resume.json`

Although specifying url in the `picture` should also work, is your resume published somewhere?

**Comment by mudassir0909** [comment]
Btw your resume looks fine http://registry.jsonresume.org/jamespedwards?theme=elegant

what's the issue?

**Comment by mudassir0909** [comment]
On a side note, this resume supports markdown, I see some urls in your work experience highlights which can be make more accessible with markdown

**Comment by jamespedwards42** [comment]
The one published to the registry is old, I need to delete that. Here is the latest: [jamespedwards42.github.io/resume/](https://jamespedwards42.github.io/resume/) .  Also, I am using [hackmyresume](http://please.hackmyresume.com/) to generate the html against a local copy of this repo's master branch after running npm install.  

I have also tried no picture field in the json, and just an empty string.  When I do that, I just get an empty box, but no garbled html.  I have confirmed that mapping this email to Gravatar works on other sites that offer that feature.

Thank you for the markdown tip :) Definitely going to update that.

**Comment by mudassir0909** [comment]
umm, I'm not aware of hackmyresume but maybe it is messing up the conversion?

![capture](https://cloud.githubusercontent.com/assets/1861842/16300267/a847597a-395c-11e6-9ec2-b588d0e7fbe7.PNG)

Because if you look at the above screenshot, the `src` attribute is being populated with an `<a>` tag instead of just the url, could you try publishing on jsonresume & see if the issue still occurs?

**Comment by jamespedwards42** [comment]
Yes, I'm pretty sure it is an issue with hackmyresume now, sorry for the hassle and thank you for all the help.  I wanted to replicate the usage by pointing to a local install of this theme from json resume but I didn't see an obvious way... Works just fine, as expected with `resume -t elegant`.

**Comment by yageek** [comment]
I have the same issue. This is apparently due to the fact that the package "themes-utils" do not specify the protocol to retrieve the gravatar url. I just created a PR to solve this.
