### ISSUE TITLE
linked skills styling

### ISSUE THREAD

**Issue by oupala** [mudassir0909/jsonresume-theme-elegant#81]
Linked skills styling is not very easy to read: it is in blue on a light blue background. When hovered, it became dark blue on a light blue background and underlined. Both are not very easy to read.

In my opinion, the linked styling should follow the unlinked styling: in white on a light blue background, underlined when hovered.

Linked or not the styling with a border looks like a button, and hence is intuitively clickable.

Create linked skills by the following markdown:

``` json
  "skills": [
    {
      "name": "tools",
      "level": "Master",
      "keywords": [
        "[git](http://fr.wikipedia.org/wiki/Git)",
        "[wiki](http://fr.wikipedia.org/wiki/Wiki)"
      ]
    }
  ]
```

**Comment by mudassir0909** [comment]
I'm wondering whether this is the right way to do linked styling, because if your keywords in itself are markdown formatted, they won't do well with the search(in case we have one in future). Basically your resume won't show up if someone searches for the `keyword` `git` or `wiki`

This could perhaps need a support in schema where you could do something as follows

```
  "skills": [
    {
      "name": "tools",
      "level": "Master",
      "keywords": [
        {
           "name": "git",
           "url": "http://fr.wikipedia.org/wiki/Git"
        },
      ]
    }
  ]
```

And theme would ensure each skill if has an url is linked appropriately. You could actually create a new issue on https://github.com/jsonresume/resume-schema

**Comment by mudassir0909** [comment]
Although for now I can fix the css styling :)

**Comment by oupala** [comment]
I've juste create a new issue in `resume-schema`.

In the meantime, I would be pleased if you can take care of the css styling...

**Comment by mudassir0909** [comment]
@oupala I had forgotten about this, my bad! `keywords` do not support markdown at the moment, how did you see links?

<img width="545" alt="screen shot 2016-11-10 at 1 27 32 pm" src="https://cloud.githubusercontent.com/assets/1861842/20168685/7504daa0-a749-11e6-90f1-5712b8c74363.png">

**Comment by oupala** [comment]
I see standard skills written in **white** on a **light blue** background, and linked skills in **dark blue** on a **light blue** background.

![screenshot](https://cloud.githubusercontent.com/assets/13458743/20566861/e2d86446-b196-11e6-91b6-ef503ba06164.png)

You can see that **dark blue** on a **light blue** background is not easy to look at.

**Comment by mudassir0909** [comment]
I understand the concern about the styling which I'll fix but I'm curious on how you got them as links in the first place, because the theme doesn't support markdown for `keywords`

**Comment by oupala** [comment]
Well, it does in fact.

Here is my json:

```json
    {
      "name": "outils de communication",
      "level": "Master",
      "keywords": [
        "[markdown](http://fr.wikipedia.org/wiki/Markdown)",
        "remark",
        "reveal"
      ]
    },
```

And `master` is not rendered.

**Comment by mudassir0909** [comment]
Are you sure you're directly using this theme via jsonresume & not from hackmyresume or something? Since, I haven't yet implemented markdown support inside the skill keywords because of [this](https://github.com/mudassir0909/jsonresume-theme-elegant/issues/81#issuecomment-241185002)

**Comment by oupala** [comment]
You're right, I'm using hackmyresume.

You mean that hackmyresume is adding features to your theme?

**Comment by mudassir0909** [comment]
yes, someone must have forked the theme, modified it & added it on hackmyresume. It'll be better if you take this issue to that repository after you find which one it is. Closing this until then.

This theme at the moment is only supposed to support jsonresume

**Comment by oupala** [comment]
hackmyresume is able to use your theme without needing to be forked. I think we can say that hackmyresume is *natively* compatible with jsonresume theme.

See my `package.json` dependencies:

```json
  "dependencies" : {
    "hackmyresume" : "^1.8.0",
    "jsonresume-theme-elegant" : "^1.3.0"
  }
```

There is still a styling issue on which you can do something. Maybe you can reopen the issue?

**Comment by mudassir0909** [comment]
Can you please check & confirm that because if you look at the source code I'm not at all processing skills as markdown. So, someone must be doing that, right? can you please look who's doing that? 

My suggestion would be to fork this theme, modify as per hackmyresume needs & use it. Since, this is aimed at JSONResume only.

**Comment by oupala** [comment]
I'm using hackmyresume v1.9.0-beta and this does not work any more. :-(

You say that jsonresume-theme-elegant aims at JSONResume only, but hackmyresume say that they try to be a compatible alternative to JSONResume that offer a local only solution (where JSONResume needs a JSONResume server and an internet access).
