### ISSUE TITLE
wikipedia links not correctly rendered

### ISSUE THREAD

**Issue by oupala** [mudassir0909/jsonresume-theme-elegant#82]
It appears that wikipedia links are not correctly rendered.

`"[jenkins](https://fr.wikipedia.org/wiki/Jenkins_(logiciel))"`

is rendered as

`<span class="label label-keyword"><a href="https://fr.wikipedia.org/wiki/Jenkins_(logiciel">jenkins</a>)</span>`.

It looks bad and the link is wrong (hence leading to a 404 error).

When I debug `markdown-it` standalone (v7.0.1), it works:

``` node
>node
> var markdown = require('markdown-it')({
...     breaks: true
... })
> markdown.render("[jenkins](https://fr.wikipedia.org/wiki/Jenkins_(logiciel))") 
'<p><a href="https://fr.wikipedia.org/wiki/Jenkins_(logiciel)">jenkins</a></p>\n'
```

You should maybe switch to a more recent version of markdown-it in your `package.json`. Maybe markdown-it v7 fixes this bug.

**Comment by mudassir0909** [comment]
I just tested `[jenkins](https://fr.wikipedia.org/wiki/Jenkins_(logiciel))` with v6 & it works, reopen if the error persists

**Comment by oupala** [comment]
As tested it again and it works well now. Dunno what changed...
