### ISSUE TITLE
Static duration display for items with no end date ("Present") will eventually be wrong

### ISSUE THREAD

**Issue by melo0187** [mudassir0909/jsonresume-theme-elegant#83]
When having items without end date, for example for your current job, omitting the attribute `endDate` leads to the word `Present` being displayed instead and this is perfectly fine.

However you do also display the duration between start and end date. This calculation happens at build time using the system time at the time of build and thus will always be wrong eventually.
Take [my CV](https://melo.myds.me) for example. Although start date for my current job is January 2016, it displays a duration of 5 instead of 9 months, simply because of the fact that I last updated my CV back in June.

Maybe adding a script tag inside the generated html that takes care to calculate the duration for this cases based on the viewer's current system time very much like the calculation performed during the generation of the html could solve this problem?

**Comment by mudassir0909** [comment]
I could see 9 months or did you update your CV recently?

<img width="946" alt="screen shot 2016-10-17 at 1 32 10 pm" src="https://cloud.githubusercontent.com/assets/1861842/19429730/d1a4498c-946e-11e6-96a7-11ce07616b52.png">

**Comment by melo0187** [comment]
I updated just yesterday ^^
However this duration is "hardcoded" into the HTML, so it will stay on 9 months and thus become wrong by next month.

**Comment by mudassir0909** [comment]
This is weird, AFAIK themes are being cached & not the resumes. You can see the sourcecode of the server here

https://github.com/jsonresume/theme-manager/blob/master/lib/theme.js#L23

It calls the `theme.render()` method everytime you access the resume profile. My resume was last published on **July 13 2016** (I've a habit of [committing resume changes](https://github.com/mudassir0909/resume/commits/master) to Github, that's how I know the last published date)

And [my resume](http://registry.jsonresume.org/mudassirali) shows the correct duration

--------------

> However this duration is "hardcoded" into the HTML, so it will stay on 9 months and thus become wrong by next month.

No, nothing is hardcoded, if you look at the [source code of this theme](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/index.js#L104). Whenever `theme.render()` is invoked by theme server, the theme recalculates the duration as of today.

---------------

Although, I'd like to see why it happened in your case, maybe let's keep this issue open for like a month & see ?

**Comment by melo0187** [comment]
Hi, thanks for your feedback. I believe I now see my problem.

Maybe I am not using this as intended. What I have done is building something on my own that is similar to [HackMyResume](http://please.hackmyresume.com).

It takes my two json files (English and German) and applies different themes (yours and [this one](https://github.com/melo0187/jsonresume-theme-paper-ger)), removes some private information for the web versions. I have this in a git repo and a Jenkins job getting notified of pushes to that repo. The job grabs the json files and my custom generator, builds the html files and moves them to my servers web folder.

So my html remains unchanged while the official server seems to rebuild the html every time. This is why the duration being generated during `render()` is not a problem when hosting the resume on the official registry. For my use case however it leads to the mentioned problem.

So what do you think? Would it be out of scope to add a script to the generated html to calculate the duration at the time of page visit?

**Comment by mudassir0909** [comment]
Ah, Hackmyresume again. Well, this theme is intended to work for themes published on [jsonresume](https://jsonresume.org/)

So yes, any changes that would be needed for HackMyResume is definitely out of the scope of this repository. Better solution would be to fork this resume, make necessary changes & use that one for HackMyResume instead.

**Comment by melo0187** [comment]
Alright, I can understand.
Will make a fork then and try to find my old jQuery skills to get this done ^^

**Comment by mudassir0909** [comment]
But will you have your `json` file on the client ?

**Comment by melo0187** [comment]
Who is the client from your perspective? The visitor's browser?
I won't have the json file there.
Actually after the cv has been rendered I want a stand-alone html that I can distribute independent of the json. The json remains in my git repo.

I was thinking of having a script that reads the final result in the html, for example "Jan, 2016 - Present". When someone loads the html, the script could run after the document loaded, read "Jan, 2016 - Present", convert this to 01.01.2016 and current time, do a diff calculation and put the result into the html element for the duration, overwriting what was calculated by `render()`.
What do you think about that?

**Comment by mudassir0909** [comment]
Sounds fair, since you'll have the html precompiled. One thing you could is that since you're gonna fork the theme, just add appropriate css selectors on elements that contain date related information, so that it'll be easier for your script to find them. For example(The theme doesn't have these css classes, I just added for the illustration):

<img width="563" alt="screen shot 2016-10-19 at 1 05 53 pm" src="https://cloud.githubusercontent.com/assets/1861842/19509568/f7d8b694-95fc-11e6-80d1-aae32a68c231.png">

You could do `$(".js-duration-wrapper")` to get all duration related elements & then read the content of `.js-date-range`, do the calculation & update the content inside `.js-duration`.

**Comment by melo0187** [comment]
I put two hours into this yesterday and can see how right you are.

Since the current html semantics were not meant for my use case, selecting the span with the range, calculating the diff, then selecting the span with the clock icon and the duration text but only replacing the duration text while preserving the clock icon is somewhat cumbersome.
I will definitely wrap the duration in its own element and add css classes to make all of the above cleaner.
I added both moment.js and the moment.js plugin for `preciseDiff()`already. This way I can have the same calculation with the same precision as you have in `render()`.

Last thing I need to understand is how to cleanly reduce the `preciseDiff()` output to show only a sensible amount of information. The output for example is like `0 years 9 months 18 days etc.`
After your theme was rendered only 9 months is displayed.
Does `preciseDiff()`return a different format for you in your `render()` function or do you have implemented a way to reduce this output to a meaningful minimum and I just didn't spot this in the theme`s code?

**Comment by melo0187** [comment]
@mudassir0909 just for the record, I have a first working version [here](https://github.com/melo0187/jsonresume-theme-elegant).

It is working but quite dirty I think, because I had to add moment.js from cdn as another script in the scripts.jade and worse I had to copy-paste the moment-precise-range.js source into scripts.jade as well.

But than again you included your own version of moment-precise-range.js ...
If I find the time I will ditch that, add moment-precise-range as dependency through NPM and include the scripts from node_modules into scripts.jade .
This would make it cleaner and also ensure that the same libraries for duration calculation are used when calculating the duration during `render` or in the browser on document load.

Maybe this might be a good opportunity to look into browserify, which might help with further improving this topic =)

**Comment by mudassir0909** [comment]
The code for duration calculation can be found [here](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/index.js#L104) I don't do anything on top of it. And [this line](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/moment-precise-range.js#L96) ensures you don't get `0 years`, maybe put a `debugger` & see what's going on?

**Comment by melo0187** [comment]
I got how it is done in your code. I just was surprised by the fact that you have moment-precise-range.js in your repository. For my first iteration of getting things done on the client side I added the source of moment-precise-range as found in the official github repo to the [script.jade](https://github.com/melo0187/jsonresume-theme-elegant/blob/master/jade/scripts.jade#L5) and it is different than what you have in your repo. This is where the different behavior came from.
I now basically added what you do inside your version of the `preciseDiff()` method around my call of the "original" `preciseDiff()` method, as can bee seen [here](https://github.com/melo0187/jsonresume-theme-elegant/blob/master/jade/scripts.jade#L168)

I don't like my approach of copy pasting other people's code anyway, so I will try to fix this in the future by using browserify.

As a start I think your version of moment-precise-range.js should be removed and the appropriate npm package added as dependency. This one [here](https://www.npmjs.com/package/moment-precise-range-plugin) looks good and is where I copy-pasted from for now.
The custom part about rolling the end date to start of next day and reducing the output to what makes sense for a CV would go around the `preciseDiff()` usage.
After that we have a clearly defined dependency instead of copy-pasted and customized code and we would have the first step to create a browserify bundle of momentjs and moment-precise-range-plugin that could be inlined in the scripts.jade file, thus guaranteeing that exactly the same libs are used to calculate the duration both on the server and the client.

Maybe I can get this done this weekend. Would you like a PR containing everything but the front end changes?

**Comment by mudassir0909** [comment]
yes, my bad! I was in a hurry so just copied & modified the file as per my needs

Assuming the PR is going to be about `preciseDiff`, sure :)
