### ISSUE TITLE
Avatar generation 

### ISSUE THREAD

**Issue by paskal** [mudassir0909/jsonresume-theme-elegant#85]
Hello, Mudassir!

I am having a problem with this awesome theme, when I do generate my resume with command `hackmyresume BUILD resume.json TO ../public/cv/elegant.html -t jsonresume-theme-elegant`, I've got profile picture generated improperly. Here is related resume.json part:

```
{
    "basics": {
        "picture": "https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200"
    }
}
````
Here is expected result:
```
<...> src="https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200" itemprop="image"<...>
```
Here is what theme generates for me:
```
<...> src="<a href="https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200">https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200</a>" itemprop="image"<...>
```
What is happening is on some stage link is converted to `a href` and included like that into `src` property of the image. I'll be glad to give you my environment information, but please tell me which will be relevant there.

**Comment by mudassir0909** [comment]
umm, does this work well when you try this with `resume` (JSON Resume CLI) ? I feel hackmyresume is doing something on top of this

**Comment by paskal** [comment]
Thank you for advise, @mudassir0909!
```diff
[root@umonkey cv]# egrep 'src.+gravatar.+center-block"/>' elegant-* -o
elegant-hackmyresume.html:src="holder.js/100x100" alt="Dmitry Verhoturov" src="<a href="https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200">https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200</a>" itemprop="image" class="media-object img-circle center-block"/>
elegant-resume-cli.html:src="holder.js/100x100" alt="Dmitry Verhoturov" src="https://www.gravatar.com/avatar/8b2d47d99e6af64b89e6a0721e3485eb?s=200" itemprop="image" class="media-object img-circle center-block"/>
```
I'll report this problem to hackmyresume team.
