### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by paskal** [mudassir0909/jsonresume-theme-elegant#86]
Hello!

I've tried to add telegram support myself, but stuck with icomoon changes. Could you please update the theme to support it?
Here is my patch on everything except icomoon:
```diff
diff --git a/README.md b/README.md
index af57570..a3f584f 100644
--- a/README.md
+++ b/README.md
@@ -27,6 +27,7 @@ The profiles are shown in the order in which they are specified in the `basics.p
 * googleplus
 * gratipay
 * hackernews
+* telegram
 * lastfm
 * linkedin
 * pinterest
diff --git a/assets/css/theme.css b/assets/css/theme.css
index 9a17a57..e30e451 100644
--- a/assets/css/theme.css
+++ b/assets/css/theme.css
@@ -55,6 +55,9 @@
 .icon-linkedin:before {
     content: "\f08c";
 }
+.icon-telegram:before {
+    content: "\f2c6";
+}
 .icon-twitter:before {
     content: "\f099";
 }
@@ -630,6 +633,14 @@ body {
   text-decoration: none;
   color: #005983;
 }
+.link-telegram {
+  color: #0088cc;
+}
+.link-telegram:hover,
+.link-telegram:focus {
+  text-decoration: none;
+  color: #007cba;
+}
 .link-skype {
   color: #12a5f4;
 }
diff --git a/assets/less/info_card_styles.less b/assets/less/info_card_styles.less
index 10378c9..2b9e922 100644
--- a/assets/less/info_card_styles.less
+++ b/assets/less/info_card_styles.less
@@ -91,6 +91,7 @@
 .link-twitter { .make-social-link(@twitter-color); }
 .link-blog { .make-social-link(@rss-feed-color); }
 .link-linkedin { .make-social-link(@linkedin-color); }
+.link-telegram { .make-social-link(@telegram-color); }
 .link-skype { .make-social-link(@skype-color); }
 .link-instagram { .make-social-link(@instagram-color); }
 .link-stackoverflow { .make-social-link(@stackoverflow-color); }
diff --git a/assets/less/variables.less b/assets/less/variables.less
index cf05176..0171794 100644
--- a/assets/less/variables.less
+++ b/assets/less/variables.less
@@ -18,6 +18,7 @@

 // Social variables;
 @github-color: #454545;
+@telegram-color: #0088cc;
 @twitter-color: #33ccff;
 @soundcloud-color: rgb(232, 130, 45);
 @rss-feed-color: #f36f24;
```

**Comment by mudassir0909** [comment]
Thanks for the PR, I'll add the icon support & merge

**Comment by paskal** [comment]
@mudassir0909, I guess a page in wiki on how to make such change and prepare a complete PR will be great — I don't know icomoon settings and it's only reason I can't generate it.
If that's happening once in years, then it's ok to leave things where they are.

**Comment by mudassir0909** [comment]
@paskal The current process is quite messy in the sense that I'm converting the font to base64 & inlining the huge chunk of the converted text since we cannot serve assets at the moment. But recently I found https://unpkg.com/#/. So, I'll set this thing up & then will create a wiki page so that others can contribute as well

**Comment by mudassir0909** [comment]
I've added telegram icon & also this [wiki page](https://github.com/mudassir0909/jsonresume-theme-elegant/wiki/Adding-a-new-icon) for future reference in case if somebody needs to add an icon.

Do you know what's the url format for telegram given the `username`? For example

Twitter --> twitter.com/username
Skype --> skype:username?call

**Comment by paskal** [comment]
You're awesome!
Format is following (an [example](https://telegram.me/Paskal_07)):
`https://telegram.me/username`

**Comment by mudassir0909** [comment]
I pushed the relevant changes & telegram is now supported, include the following json under `basics.profiles` 

```
      {
        "network": "telegram",
        "username": "Paskal_07"
      }
```

Although we might have to wait for https://github.com/jsonresume/theme-manager/issues/23 to be fixed before seeing this live. Thanks! 👍
