### ISSUE TITLE
PDF print improvements

### ISSUE THREAD

**Issue by paskal** [mudassir0909/jsonresume-theme-elegant#87]
Hello, @mudassir0909!

I generate pdf version of resume using `xvfb-run wkhtmltopdf elegant.html elegant.pdf` and it looks pretty solid, however there is some room for improvement. I guess, you could see everything I'm mentioning  by resizing browser window to some particular size which "wkhtmltopdf" use by default.

* Languages section looks a bit out-of-line, I guess these blocks if they don't fit on the line should be centered on the other one:
![image](https://cloud.githubusercontent.com/assets/712534/21292972/fdf0175e-c52f-11e6-8626-ca9a96814e33.png)

* Some blocks have to tied together to prevent situations like on screenshot:
![image](https://cloud.githubusercontent.com/assets/712534/21292993/95c5076a-c530-11e6-9cc0-d3aff1480882.png)
I guess header have to be tied to first line of context.

**Comment by mudassir0909** [comment]
yea, I think we have page break related css styles which can be applied on certain divs. I'll look into the languages thing as well

**Comment by paskal** [comment]
Here is how it was managed in another theme via css: https://github.com/LinuxBozo/jsonresume-theme-kendall/commit/fcda74eb131f72df02a34a10107b74d72c752f0a
Also I've talked with professional HR specialist and have couple of suggestions based on that talk:
![image](https://cloud.githubusercontent.com/assets/712534/21465073/6f6939a8-c9ac-11e6-98c4-f30928016a85.png)
1. `Background` takes a lot of space and completely unnecessary there, it could be removed and you will lose nothing.
![image](https://cloud.githubusercontent.com/assets/712534/21465077/a1a1d380-c9ac-11e6-8f04-ce54423bd70a.png)
![image](https://cloud.githubusercontent.com/assets/712534/21465080/c497851a-c9ac-11e6-8c78-505feb3aa5af.png)
2. Social buttons should be more print-friendly, for that link should be printed as a text next to the icon when you're printing the page. Same goes for work links and any other links which you could find in the document - printed version on paper should have them written in black, otherwise they will be lost.
![image](https://cloud.githubusercontent.com/assets/712534/21465085/fec4b14a-c9ac-11e6-9937-238c4cdb67a9.png)
3. Skills section could include level of knowledge, it's a must-have feature for most resumes.
![image](https://cloud.githubusercontent.com/assets/712534/21465092/5253eb8c-c9ad-11e6-9339-7ad5a04a0ec6.png)
4. Most important part of the resume, job title, is grey and small. It should be more visible than my name, actually.
![image](https://cloud.githubusercontent.com/assets/712534/21465093/715a03fe-c9ad-11e6-8a20-e81ac4c98fae.png)
5. Text font is really small, it should be cool to have ability to adjust it's size to make it more reader-friendly.
These points are just for discussion, it's up to you to think about them or to ignore them.

**Comment by mudassir0909** [comment]
@paskal Thanks for these points, 

1. Agree with this
2. I wouldn't use this theme for print because it never was on my priority list when I was building this(Although I tried to make it look nice on print), I'd definitely build a print based theme soon or there are already some which are optimised for print. I'm happy for a PR on this
3. is already supported, [if you look at this](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/index.js#L113-L118), if you have skill `level` defined then it'll be shown(provided it falls under the predefined list of values). Maybe I should update README on this
4. & 5. can be discussed

**Comment by paskal** [comment]
@mudassir0909, that's just an opinion I've got from HR, I think you are creator and demiurg and you're only one who should decide if there is something to be done or it should be left as it is now.

**Comment by mudassir0909** [comment]
hehe but I really appreciate the feedback! will definitely implement some of these, thanks :)
