### ISSUE TITLE
External fonts

### ISSUE THREAD

**Issue by inakiabt** [mudassir0909/jsonresume-theme-elegant#93]
Is there a way to use external fonts? I want to use this theme hosted on github pages, but it uses local fonts that I don't have. Maybe using external urls for fonts would be better for these cases.
Thanks.

**Comment by mudassir0909** [comment]
Umm, I think you can fork this repo, modify [this line](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/pug/scripts.pug#L32) to load your own font, update [this line in the stylesheet](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/assets/less/base.less#L6) & you should be good to go, right? Or maybe I'm missing something?

If you do want the theme to support specifying custom fonts, then right now there is no way to do that using the current schema. I hope once the schema starts supporting the concept of metadata, we should be able to achieve that but for now forking is the way to go especially when you want to host it on GitHub pages.

**Comment by inakiabt** [comment]
Thanks! I think the issue (at least in my case) is with the icons font: https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/assets/icomoon/style.css#L3
It uses a local *iconmoon* font, so when I export my resume to HTML locally (using `resume-cli`), the *iconmoon* font aren't be there.

Maybe these could be used instead?
https://cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.2/fonts/icomoon.eot
https://cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.2/fonts/icomoon.svg
https://cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.2/fonts/icomoon.ttf
https://cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.2/fonts/icomoon.woff

I found them here: https://cdnjs.com/libraries/bootcards

**Comment by mudassir0909** [comment]
Ah, no I already did that change. If you see the compiled stylesheet it uses the url served by [unpkg](https://unpkg.com/#/) 

See [this line](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/assets/css/theme.css#L289), also see [icons.less](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/assets/less/icon.less)

**Comment by inakiabt** [comment]
You're right. Opening the local HTML on Chrome was causing an error loading `//unpkg` fonts. I didn't see that after your comment.
Thanks.
